# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath D:/modeltech_pe_10.4c/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.cache/wt [current_project]
set_property parent.project_path D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files d:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/TestData/mips_31_mars_simulate.coe
read_verilog D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/new/parameter.vh
read_mem {
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/Mars/test_addi.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_addiu.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_lui.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_add.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_addu.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_and.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_andi.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_lwsw.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_lwsw2.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_nor.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_or.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_ori.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_sll.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_sllv.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_slt.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_slti.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_sltiu.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_sltu.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_sra.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_srav.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_srl.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_srlv.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_sub.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_subu.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_xor.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_xori.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_beq.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_bne.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_j.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_jal.mem
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/imports/mem/test_jr.mem
}
read_verilog -library xil_defaultlib {
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/new/RegFiles.v
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/new/PCReg.v
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/new/NPC.v
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/new/MUX4.v
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/new/MUX2.v
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/new/IRAM.v
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/new/EXT.v
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/new/DRAM.v
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/new/ControlUnit.v
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/new/ALU.v
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/new/ADD.v
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/new/Top.v
  D:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/new/sccomp_dataflow.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top sccomp_dataflow -part xc7a100tcsg324-1


write_checkpoint -force -noxdef sccomp_dataflow.dcp

catch { report_utilization -file sccomp_dataflow_utilization_synth.rpt -pb sccomp_dataflow_utilization_synth.pb }
