# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/ip/IPIRAM/IPIRAM.xci
# IP: The module: 'IPIRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/ip/IPIRAM/IPIRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IPIRAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/ip/IPIRAM/IPIRAM.xci
# IP: The module: 'IPIRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/4x10msv/LearingFiles/ComputerOrganization/MIPS31/MIPS31_sc/MIPS31_sc.srcs/sources_1/ip/IPIRAM/IPIRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IPIRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
